name: DocFX

on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Update index.md with README content
      run: |
        # Extract the frontmatter from index.md
        frontmatter=$(sed -n '1,/^---$/p' index.md)
        # Copy README content
        readme_content=$(cat README.md)
        # Combine frontmatter with README content
        echo "$frontmatter" > index.md
        echo "$readme_content" >> index.md

    - run: dotnet tool update -g docfx
    - run: docfx ./docfx.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './_site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
